### PR TITLE
Adds contributing

### PR DESCRIPTION
**Pull request by pixunil**
- Includes updated code style
- Includes common pitfalls

Best viewed by using the "rich diff" option.

### CODE REVIEW

**Review by jonaskordt — APPROVED** [review]
Wonderful 🚟🚃🚋🚞🚝🚄🚅🚈🚂🚆🚇🚊🚉

**Review by kiragrammel — APPROVED** [review]
☺️👍🏼🚃

**Review by lpfennigschmidt — APPROVED** [review]
I like it, but maybe we can discuss in a group, whether we missed something or not :D

**Review by felix-gohla — CHANGES_REQUESTED** [review]
Maybe we could add an example for block formatting (i.e. block arguments and block instance variables)? :+1:
Do remaining user stories belong into this file and do we even want to include those into the repo?

**Review by felix-gohla — APPROVED** [review]
Great 😊

**Pull request merged**
